"""initial schema

Revision ID: c8a5f25bc447
Revises:
Create Date: 2026-04-30 15:12:29.132132

Dialect notes:

- Postgres is the production target; SQLite is dev-only. The schema is
  portable: ``sa.JSON`` maps to ``JSONB`` on Postgres and ``JSON`` on SQLite,
  ``sa.Enum`` creates a named type on Postgres and a ``CHECK`` constraint on
  SQLite, ``sa.DateTime`` uses ``TIMESTAMP WITHOUT TIME ZONE`` / ``DATETIME``.
- SQLite cannot ``ALTER TABLE`` most columns. Future column changes on this
  schema must use ``with op.batch_alter_table(...)`` so they work on both
  backends.
- The ``scanstatus`` enum type is created automatically by Postgres on the
  first ``op.create_table('scans', ...)`` and is dropped explicitly in
  ``downgrade()`` so a re-upgrade on Postgres doesn't trip over a leftover
  type. The SQLite branch is a no-op.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c8a5f25bc447"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "environments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("kubecost_url", sa.String(length=512), nullable=False),
        sa.Column("auth_token_encrypted", sa.Text(), nullable=True),
        sa.Column("aws_region", sa.String(length=64), nullable=False),
        sa.Column("cluster_name", sa.String(length=255), nullable=True),
        sa.Column("last_connection_check", sa.DateTime(), nullable=True),
        sa.Column("last_connection_ok", sa.Boolean(), nullable=False),
        sa.Column("last_connection_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "scans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("environment_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("QUEUED", "RUNNING", "COMPLETED", "FAILED", name="scanstatus"),
            nullable=False,
        ),
        sa.Column("progress_message", sa.String(length=255), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("window", sa.String(length=16), nullable=False),
        sa.Column("raw_data", sa.JSON(), nullable=True),
        sa.Column("digest", sa.JSON(), nullable=True),
        sa.Column("total_cost_usd", sa.Float(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["environment_id"],
            ["environments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scan_id", sa.Integer(), nullable=False),
        sa.Column("executive_summary", sa.Text(), nullable=False),
        sa.Column("findings", sa.JSON(), nullable=False),
        sa.Column("estimated_monthly_savings_usd", sa.Float(), nullable=True),
        sa.Column("model_used", sa.String(length=128), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["scan_id"],
            ["scans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scan_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reports")
    op.drop_table("scans")
    op.drop_table("environments")
    # ### end Alembic commands ###

    # Drop the named enum on Postgres so a re-upgrade can recreate it.
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        sa.Enum(name="scanstatus").drop(bind, checkfirst=True)
